[build]
    functions = "functions"
    node_bundler = "esbuild"
    publish="public"

[functions]
    included_files = ["public/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    access-control-allow-origin = "*"